- src/packages/solid/components/Button/Button.tsx
- src/packages/solid/components/Metadata/Metadata.styles.ts
- src/packages/solid/components/Metadata/Metadata.tsx
- src/packages/solid/components/Tile/Tile.stories.tsx
- src/packages/solid/components/Tile/Tile.tsx
- src/packages/solid/utils/index.ts
- src/packages/solid/utils/useItemLayout.ts
A handful of fixes I came across while integrating with solidly-mosaic
- remove debuggers from Tile
- remove hard coded alt text from Tile.Artwork
- clean up the Tile stories
- add the useItemLayout utility
- update metadata to no longer render the title and description on top of each other in some instances
Review the Tile stories and ensure everything renders as expected
> fix: various fixes

- pnpm-lock.yaml
- src/packages/solid/package.json
- src/sandbox/package.json
This PR updates some dependency versions, moves the `@lightningjs` dependencies into peerDependencies, and enables sourcemaps for library builds
> fix: update module versions, add sourcemaps 

- src/packages/solid/components/Button/Button.stories.tsx
- src/packages/solid/components/Button/Button.tsx
- src/packages/solid/components/Icon/Icon.tsx
This PR fixes a misnamed import in Button which causes the storybook build to fail. It also cleans up the Icon tones setup
run the storybook build `pnpm run solid:build-storybook`
> fix: storybook build

- src/packages/solid/utils/mapToneToStateHook.ts
This PR updates the states type in the mapToneToStateHook to only be an array of `string` instead of an array of either `string` or `{string: boolean}`
TS error should no longer appear when assigning mapToneToStateHook to Config.stateMapperHook
> fix(utils): update mapToneToStateHook `states` type to only be arrays of strings

- .github/workflows/publish-packages.yml
- .github/workflows/publish-solid-storybook.yml
This PR adds the service account email to the git global config in the runner so we can commit changes, and removes the `on publish main` config from the storybook publish workflow
n/a
> fix: add service account email to release workflow, stop double publishing storybook

- src/packages/solid/components/Artwork/Artwork.styles.ts
- src/packages/solid/components/Badge/Badge.styles.ts
- src/packages/solid/components/Button/Button.styles.ts
- src/packages/solid/components/Checkbox/Checkbox.styles.ts
- src/packages/solid/components/Checkbox/Checkbox.tsx
- src/packages/solid/components/Column/Column.styles.ts
- src/packages/solid/components/Icon/Icon.styles.ts
- src/packages/solid/components/Key/Key.styles.ts
- src/packages/solid/components/Keyboard/Keyboard.styles.tsx
- src/packages/solid/components/Label/Label.styles.ts
- src/packages/solid/components/ProgressBar/ProgressBar.styles.ts
- src/packages/solid/components/Row/Row.styles.ts
- src/packages/solid/components/Tile/Tile.styles.ts
- src/packages/solid/templates/styles.template.ts
Updates the components to pull the default tone from the defaultTone componentConfig property instead of tone. also fixes some type issues in Checkbox
ensure all components now reference defaultTone
> fix: update componentConfig to use defaultTone instead of tone

- src/packages/solid/components/Column/Column.stories.tsx
- src/packages/solid/components/Column/Column.tsx
- src/packages/solid/components/Row/Row.stories.tsx
- src/packages/solid/components/Row/Row.tsx
- src/packages/solid/package.json
- src/packages/solid/utils/withScrolling.ts
- reworking scrolling to use 'auto' as default
- scrollIndex only used in 'auto', no other scrolling types
- changing names in api
- Check scrolling is accurate for row and column with all types of scrolling (`auto`, `lazy`, `always`, `never`).
- Check all api changes have been made in all places 
- `scrollType` now `scroll`
- `lazyScroll` now `lazy`
- `alwaysScroll` now `always`
- `neverScroll` now `none`
> fix(scrolling): addressing api changes and scrolling functionality - breaking

- src/packages/l3-ui-theme-base/theme.js
- src/shared/AppCoreExtensions.js
This PR updates the base theme to use `fontWeight: number;` instead of `fontStyle: string` to declare a text element's font weight.It also updates the shared AppCoreExtension to setup Arial 500 and Arial 300 as ubuntu bold and ubuntu regular, respectively.
storybook should now render text as expected
> fix: rename fontStyle to fontWeight

- src/packages/solid/components/Column/Column.tsx
- src/packages/solid/components/Row/Row.tsx
- src/packages/solid/utils/withScrolling.ts
- ensures accurate x value positioning on load of rows and columns when scroll type is always or edge and selectedIndex > 0 on component creation.
- runs withScrolling `onCreate` in addition to `onSelectedChanged`
- sets fallback rootPosition to 0 if no y/x value in componentRef
- updates variables in withScrolling to better articulate what values they represent
- In the `Column.stories.ts` file or the `Row.stories.ts` file,  add a selected value greater than 0 to the arguments of the story. Notice how the x and y position shift so that the focused item is shown on the screen in the desired location
- In the `Column.stories.ts` file or the `Row.stories.ts` file, remove the x or y in a story that uses auto or edge scroll, notice how scrolling now works appropriately
> fix(withScrolling): scrolls selected item to correct position on creation when selected > 0

- src/packages/solid/components/Button/Button.styles.ts
Adds config to the Button style file to incorporate styles from a theme's `componentConfig.Surface`
> feat(Button): inherit theme styles from Surface

- src/packages/solid/components/Badge/Badge.stories.tsx
- src/packages/solid/components/Badge/Badge.tsx
Creates a `badgeContainer` component that can take any number of children.
Allows `badge` to only take a title and hold text
- removes all icon related properties from the Badge props
- adds badgeContainer component
- check `Badge` and `BadgeContainer` and make sure everything works as expected
> feat(Badge): separates Badge and Badge Container

- src/packages/solid/utils/getThemeStyles.js
- src/packages/solid/utils/objectFromEntries.ts
This PR removes uses of Object.fromEntries in order to support earlier versions of chrome
- adds objectFromEntries util
- removes uses Object.fromEntries from getThemeStyles
ensure themed styles still load as expected
> fix: replace Object.fromEntries to support chrome 63

- src/packages/solid/components/Artwork/Artwork.tsx
- src/packages/solid/components/Badge/Badge.tsx
- src/packages/solid/components/Button/Button.stories.tsx
- src/packages/solid/components/Button/Button.tsx
- src/packages/solid/components/Checkbox/Checkbox.tsx
- src/packages/solid/components/Column/Column.tsx
- src/packages/solid/components/Icon/Icon.tsx
- src/packages/solid/components/Input/Input.tsx
- src/packages/solid/components/Key/Key.tsx
- src/packages/solid/components/Keyboard/Keyboard.tsx
- src/packages/solid/components/Keyboard/KeyboardSimple.tsx
- src/packages/solid/components/Label/Label.styles.ts
- src/packages/solid/components/Label/Label.tsx
- src/packages/solid/components/Metadata/Details.tsx
- src/packages/solid/components/Metadata/Metadata.tsx
- src/packages/solid/components/Metadata/Rating.tsx
- src/packages/solid/components/ProgressBar/ProgressBar.tsx
- src/packages/solid/components/Row/Row.tsx
- src/packages/solid/components/Tile/Tile.tsx
- src/packages/solid/components/Toggle/Toggle.tsx
- src/packages/solid/tsconfig.json
- src/packages/solid/types/interfaces.d.ts
- src/packages/solid/utils/chainFunctions.ts
- src/packages/solid/utils/withScrolling.ts
This PR updates our components to utilize the latest style API, as well as adding a base level prop interface for all of our components to implement
known issues: the `style` prop on Views and Texts is currently throwing a type error for props.style. the type needs to be updated to allow nested arrays
**update**: this also includes some type updates to the `chainFunctions` utility that should resolve the errors that we were attempting to resolve in PR https://github.com/lightning-js/ui-components/pull/103
- replaces all instances of `...[props.style].flat()` with `props.style`, thanks to solid's latest update to accept nested style arrays
- updates component prop types to leverage the solid node types where applicable
- adds `UIComponentProps` interface to ensure all of our components …
> fix: normalize styles

- src/packages/solid/components/CardContent/CardContent.stories.tsx
- src/packages/solid/components/CardContent/CardContent.styles.ts
- src/packages/solid/components/CardContent/CardContent.tsx
- src/packages/solid/components/Input/Input.styles.ts
- src/packages/solid/components/Tile/Tile.tsx
- src/packages/solid/utils/getDimensions.ts
- src/packages/solid/utils/getWidthByColumnSpan.ts
- src/packages/solid/utils/getWidthByUpcount.ts
- src/packages/solid/utils/index.ts
Adds a `metadataColumnSpan` and `tileColumnSpan` prop so users can control the size of cardContent
- `metadataColumnSpan` prop
- `tileColumnSpan` prop 
- change values in these added properties to see component change
> fix(CardContent): allows users to add columnSpan as prop

- src/packages/solid/utils/chainFunctions.ts
Updates chainFunctions utility to provide better type safety, and no longer assert the `Function` type, following the requests in https://github.com/lightning-js/ui-components/pull/103
> fix(chainFunctions): add loose function type for function args

- src/packages/solid/components/Checkbox/Checkbox.styles.ts
- src/packages/solid/components/Metadata/Rating.styles.ts
- src/packages/solid/components/Metadata/Rating.tsx
updates the path of icon types imports to be from Icon.types
Make sure checkbox and ratings render correctly
> fix(Solid): fix icon types imports path

- src/packages/solid/components/Radio/Radio.stories.tsx
- src/packages/solid/components/Radio/Radio.styles.ts
- src/packages/solid/components/Radio/Radio.tsx
-fixes checked types and allows radio to render 
- removes spread of styles props causing the component to fail to render
- adds modeKeys to Radio
- check to see the radio renders as it should
> fix(Solid): removes spread from styles props in Radio

- src/packages/solid/components/Metadata/Metadata.tsx
The Details component within Metadata did not have a conditional Show tag applied causing Metadata to hold space for the Details even when it's not in use. This held space was causing extra space in components where Metadata is used and Details is not needed. See **before** and **after** photos of the tile using Metadata below. Observe the extra blank space held for the nonexistent Details in the **before** photo.
> fix(Solid): update Metadata details view

- src/packages/solid/templates/stories.template
- src/packages/solid/templates/styles.template
- src/packages/solid/templates/types.template
- update templates to match new patterns
- add `types` file template
- make ComponentName easier to find and replace by wrapping it in <>
> chore: update templates to match latest patterns, wrap ComponentName placeholder in <>

- pnpm-lock.yaml
- src/packages/blits/.storybook/preview.ts
- src/packages/blits/package.json
- src/packages/blits/src/components/Badge/Badge.stories.tsx
- src/packages/blits/src/components/Badge/Badge.styles.ts
- src/packages/blits/src/components/Badge/Badge.ts
- src/packages/blits/src/components/Button/Button.stories.tsx
- src/packages/blits/src/components/Button/Button.styles.ts
- src/packages/blits/src/components/Button/Button.ts
- src/packages/blits/src/components/Icon/Icon.stories.tsx
- src/packages/blits/src/components/Icon/Icon.styles.ts
- src/packages/blits/src/components/Icon/Icon.ts
- src/packages/blits/src/components/Metadata/Details.styles.ts
- src/packages/blits/src/components/Metadata/Details.ts
- src/packages/blits/src/components/Metadata/Metadata.stories.tsx
- src/packages/blits/src/components/Metadata/Metadata.styles.ts
- src/packages/blits/src/components/Metadata/Metadata.ts
- src/packages/blits/src/components/Metadata/Rating.styles.ts
- src/packages/blits/src/components/Metadata/Rating.ts
- src/packages/blits/src/components/ProgressBar/ProgressBar.stories.tsx
- src/packages/blits/src/components/ProgressBar/ProgressBar.styles.ts
- src/packages/blits/src/components/ProgressBar/ProgressBar.ts
- src/packages/blits/src/utils/castUtils.ts
- src/packages/blits/src/utils/flexUtils.ts
- src/packages/blits/src/utils/index.ts
- src/packages/blits/src/utils/styleUtils.ts
- src/packages/blits/src/utils/textUtils.ts
New Metadata component for Blits, and some updates to style typings and utils
- Added Metadata component
- Added flexUtils to handle some of the logic we're missing as Blits has no flex yet :(
- Added styleUtils with some generic types for Component styling, all component style objects need to satisfy this type now (see any component's style for how this works)
- Added methods to search a style object for a specific property (can be deeply nested e.g. obj.foo.bar) - search is prioritised based on tone and state to avoid needing to write all combinations into style objects. Props will be searched in this priority: Tone + State -> State -> Tone -> Base
- Updated the Storybook decorator to allow object properties to be passed into components
- Updated Storybook decorator to focus on the …
> feat(Blits): Metadata Component + Standardised Style Types
