lightning-js/ui-components

src/packages/solid/.storybook/AppCoreExtensions.ts
src/packages/solid/.storybook/preview.tsx
src/packages/solid/vite.config.js

See the comment in AppCoreExtensions.ts for more info.

Workaround for storybook-static issue

---

src/packages/solid/.storybook/AppCoreExtensions.js

Shouldn't have deleted this...

undo removing file

---

src/packages/solid/components/Icon/Icon.stories.tsx
src/packages/solid/components/Icon/Icon.styles.tsx
src/packages/solid/components/Icon/Icon.tsx
src/packages/solid/components/Icon/index.ts
src/packages/solid/index.ts

**JIRA**
no JIRA ticket
**Description**
Allows the use of states with the icon and the use of the color from props rather than only style

feat(Icon): adding states and correct color control to icon

---

pnpm-lock.yaml
src/packages/solid/components/Badge/Badge.test.tsx
src/packages/solid/components/Badge/Badge.tsx
src/packages/solid/components/Badge/__snapshots__/Badge.test.tsx.snap
src/packages/solid/components/Button/Button.test.tsx
src/packages/solid/components/Button/__snapshots__/Button.test.tsx.snap
src/packages/solid/components/Button/index.ts
src/packages/solid/package.json
src/packages/solid/test-utils.jsx
src/packages/solid/vite.config.js

Tests are running. Need to release change to solidjs - but this should get us started with writing tests

feat: tests with vitest

---

src/packages/solid/components/Button/Button.stories.tsx
src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/Button/Button.tsx

child controls title rather than having a prop title

fix(Button): child controls title

---

src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/ProgressBar/ProgressBar.stories.tsx
src/packages/solid/components/ProgressBar/ProgressBar.styles.ts
src/packages/solid/components/ProgressBar/ProgressBar.tsx

**JIRA**
NO JIRA
**Description**
Update default renderer in progressBar story as well as formatting color props

fix(ProgressBar): adding renderer and color props

---

src/packages/solid/components/Tile/Tile.stories.tsx
src/packages/solid/components/Tile/Tile.tsx

adding stories to show how we can move components around the tile

feat(Tile): adding customizable examples

---

src/packages/solid/tsconfig.json

quick config fix for solid-ui's tsconfig

fix: update solid-ui tsconfig theme path

---

src/packages/solid/.storybook/preview-head.html
src/packages/solid/.storybook/preview.tsx
src/packages/solid/components/Column/Column.styles.ts
src/packages/solid/components/Column/Column.tsx

adjusting the styles file to match the new themes and tone format

fix(Column): refactoring styles file

---

.eslintrc.json
pnpm-lock.yaml
src/packages/solid/components/Badge/Badge.stories.tsx
src/packages/solid/components/Badge/Badge.styles.ts
src/packages/solid/components/Badge/Badge.tsx
src/packages/solid/components/Button/Button.stories.tsx
src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/Button/Button.tsx
src/packages/solid/components/Button/index.ts
src/packages/solid/components/Icon/Icon.stories.tsx
src/packages/solid/components/Icon/Icon.styles.ts
src/packages/solid/components/Icon/Icon.tsx
src/packages/solid/components/ProgressBar/ProgressBar.styles.ts
src/packages/solid/components/ProgressBar/ProgressBar.tsx
src/packages/solid/components/Tile/Tile.tsx
src/packages/solid/index.ts
src/sandbox/index.html
src/sandbox/package.json
src/sandbox/pages/App.jsx
src/sandbox/vite.config.js
vite.config.js

This PR includes the following changes:
-  updates the Badge style file to be theming compatible
- disables eslint rules for solid styling(these are meant for CSS and don't apply to this code base)
- cleans up our vite configs a bit

fix(badge): update badge style file

---

src/packages/solid/components/Column/Column.styles.ts
src/packages/solid/components/Row/Row.styles.ts
src/packages/solid/components/Row/Row.tsx
src/packages/solid/package.json
src/packages/solid/vite.config.js

- updating Row styles to account for tone

feat(Row): updating row styles

---

pnpm-lock.yaml
src/packages/solid/components/Column/Column.stories.tsx
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/ProgressBar/ProgressBar.tsx
src/packages/solid/components/Row/Row.stories.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/components/Tile/Label.tsx
src/packages/solid/utils/chainFunctions.ts
src/packages/solid/utils/index.ts

adjusting Row and Column to account for changes made to clipping on renderer
Removing clipping from Row and Column
Check that Row and Column scroll correctly and do not have any components clipped out.

fix(Scrolling): removing clipping from Row and Column

---

src/packages/solid/.storybook/preview.tsx
src/packages/solid/components/Key/Key.stories.tsx
src/packages/solid/components/Key/Key.styles.ts
src/packages/solid/components/Key/Key.tsx
src/packages/solid/components/Keyboard/Keyboard.stories.tsx
src/packages/solid/components/Keyboard/Keyboard.styles.tsx
src/packages/solid/components/Keyboard/Keyboard.tsx
src/packages/solid/components/Keyboard/KeyboardSimple.tsx
src/packages/solid/components/Keyboard/KeyboardSingle.tsx
src/packages/solid/components/Keyboard/index.ts
src/packages/solid/components/Row/Row.stories.tsx

LUI-1316
Creating Simply Keyboard Component

feat(Keyboard): creation

---

src/packages/solid/components/Checkbox/Checkbox.stories.tsx
src/packages/solid/components/Checkbox/Checkbox.styles.ts
src/packages/solid/components/Checkbox/Checkbox.tsx
src/packages/solid/components/Icon/Icon.styles.ts
src/packages/solid/components/Icon/Icon.tsx

Refactoring checkbox styles to reflect new styles configuration with toneModes

refactor(checkbox): styles

---

pnpm-lock.yaml
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/package.json
src/packages/solid/utils/assertTruthy.ts
src/packages/solid/utils/chainFunctions.ts
src/packages/solid/utils/handleNavigation.ts
src/packages/solid/utils/index.ts

move row and column in ui-comp

---

src/packages/solid/components/Keyboard/Keyboard.styles.tsx
src/packages/solid/components/Keyboard/index.ts
src/packages/solid/index.ts
src/packages/solid/package.json

fix: missing exports

---

src/packages/solid/.storybook/preview.tsx

fix: preview cleanup render when switching pages

---

.github/workflows/publish-packages.yml
.github/workflows/publish-solid-storybook.yml
README.md
lerna.json
package.json
pnpm-lock.yaml
src/packages/l3-ui-theme-base/CHANGELOG.md
src/packages/l3-ui-theme-base/package.json
src/packages/solid/CHANGELOG.md
src/packages/solid/LICENSE
src/packages/solid/package.json

This PR adds lerna for automatic versioning, and leverages pnpm publish to publish packages from CI
we'll see how well it works once its merged

feat: add lerna

---

src/packages/solid/utils/handleNavigation.ts

fix: nav with 0 children and non focus for selected

---

.github/workflows/publish-packages.yml

Uncomments the step to publish a storybook build on a successful release
n/a

chore: restore step to publish storybook on successful package release

---

src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/utils/handleNavigation.ts

fix: row and column use forwardFocus

---

src/packages/solid/utils/handleNavigation.ts

fix: handle no children for focus

---

package.json
pnpm-lock.yaml
src/packages/solid/components/Input/Input.stories.tsx
src/packages/solid/components/Input/Input.styles.ts
src/packages/solid/components/Input/Input.tsx
src/packages/solid/components/Input/index.ts

[LUI-1322](https://ccp.sys.comcast.net/browse/LUI-1322)
Creating an Input Component containing eyebrow text, help text, and the content of the input field. It takes a signal provided by the user that handles the key-handling of which the Input component reads from. 
Creation
- check files,
- notice how you are able to type and add characters as well as delete characters

feat(Input): adding input component

---

pnpm-lock.yaml

fix: lock file broken release

---

src/packages/solid/components/Column/Column.tsx

fix(column): typescript wrong props

---

src/packages/solid/components/Icon/Icon.tsx
src/packages/solid/components/Metadata/Details.styles.ts
src/packages/solid/components/Metadata/Details.tsx
src/packages/solid/components/Metadata/Metadata.stories.tsx
src/packages/solid/components/Metadata/Metadata.styles.ts
src/packages/solid/components/Metadata/Metadata.tsx
src/packages/solid/components/Metadata/Rating.styles.ts
src/packages/solid/components/Metadata/Rating.tsx

Updating metadata, ratings, and details styles to work with new format and tones
styles files to metadata, ratings, and details as well as applying the styles in the components
check that all styles are accounted for and applied

refactor(Metadata): updates styles files

---

pnpm-lock.yaml
src/packages/solid/components/Artwork/Artwork.styles.ts
src/packages/solid/components/Artwork/Artwork.tsx
src/packages/solid/components/Badge/Badge.tsx
src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/Button/Button.tsx
src/packages/solid/components/Checkbox/Checkbox.tsx
src/packages/solid/components/Column/Column.styles.ts
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Icon/Icon.tsx
src/packages/solid/components/Input/Input.styles.ts
src/packages/solid/components/Input/Input.tsx
src/packages/solid/components/Key/Key.styles.ts
src/packages/solid/components/Key/Key.tsx
src/packages/solid/components/Keyboard/Keyboard.styles.ts
src/packages/solid/components/Keyboard/Keyboard.tsx
src/packages/solid/components/Label/Label.tsx
src/packages/solid/components/Metadata/Details.tsx
src/packages/solid/components/Metadata/Metadata.tsx
src/packages/solid/components/Metadata/Rating.tsx
src/packages/solid/components/ProgressBar/ProgressBar.tsx
src/packages/solid/components/Row/Row.stories.tsx
src/packages/solid/components/Row/Row.styles.ts
src/packages/solid/components/Row/Row.tsx
src/packages/solid/components/Tile/Tile.tsx
src/packages/solid/package.json

makes all props styles and default styles to the components consistent
scrubs all components to use the format of merging props styles and default styles into one
check styles of all components and make sure they are getting applied correctly

fix(styles): makes all props styles and default styles to the components consistent

---

src/packages/solid/components/Toggle/Toggle.stories.tsx
src/packages/solid/components/Toggle/Toggle.styles.ts
src/packages/solid/components/Toggle/Toggle.tsx
src/packages/solid/components/Toggle/index.ts

LUI-1402
Creates a toggle that can be checked on and checked off based on the boolean `checked` property. Utilizes new style configurations with nested tones and modes.
- check the toggle on and off to see how the colors and knob positioning changes.

feat(Toggle): creates toggle

---

pnpm-lock.yaml
src/packages/solid/package.json
src/packages/solid/utils/chainFunctions.ts
src/packages/solid/utils/handleNavigation.ts

fix: minor changes to chain - update packages

---

src/packages/solid/components/FPSCounter/FPSCounter.stories.tsx
src/packages/solid/components/FPSCounter/FPSCounter.tsx
src/packages/solid/components/FPSCounter/index.ts
src/packages/solid/index.ts

feat(fps): Add FPSCounter

---

pnpm-lock.yaml

Fixes a broken lockfile thats preventing builds from being published

fix: re-run install to fix lockfile

---

package.json
pnpm-lock.yaml
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/utils/withScrolling.ts

-allows users to pass an onCreate function into Row and Column
-resolves a bug found in client apps where scrollable elements will crash if the selectedElement comes back undefined
- adds chainFunction with withScrolling and props.onCreate
- adds optional chains to selectedElement references so they'll fall back to 0 in cases where selectedElement is undefined
- ensure withScrolling doesn't crash when selectedElement is undefined
- ensure everything renders on creation

fix(Row/Column): adds chainFunction onCreate

---

pnpm-lock.yaml
src/packages/solid/.storybook/preview.tsx
src/packages/solid/package.json

update solid to 0.15

---

package.json
pnpm-lock.yaml
src/packages/solid/.storybook/preview.tsx
src/packages/solid/components/Column/Column.stories.tsx
src/packages/solid/components/Column/Column.styles.ts
src/packages/solid/components/Row/Row.stories.tsx
src/packages/solid/components/Row/Row.styles.ts
src/packages/solid/package.json

- utilizes flexBoundary so Row and Column doesn't autoresize to children width
- removes flexStart (because default is flexStart so defining it is not needed)
- removes styling defaults of height and width
- updates disposing the story so it grabs the dispose function rather than the whole object
- see that row and column get width and height from parent if not passed in directly as a prop.
- make sure row and column scroll as expected

fix(Row&Column): removes style default width and height

---

src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx

This should be standard for any components where user we use ref internally

fix: add mergeRef for Column and Row

---

src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/FPSCounter/FPSCounter.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/package.json
src/sandbox/index.jsx

fix: no need to use mergeRef

---

package.json
pnpm-lock.yaml
src/packages/l3-ui-theme-base/theme.d.ts
src/packages/l3-ui-theme-base/theme.d.ts.map
src/packages/l3-ui-theme-base/theme.js

adds theme with animation duration in ms
make sure everything looks right and theme values are coming through correctly.

fix(themes): adds theme with animation duration in ms

---

src/packages/solid/components/Radio/Radio.stories.tsx
src/packages/solid/components/Radio/Radio.styles.ts
src/packages/solid/components/Radio/Radio.tsx
src/packages/solid/components/Radio/index.ts
src/packages/solid/index.ts

Creates a new Radio component.

feat(Radio): create component

---

package.json
pnpm-lock.yaml
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx
src/packages/solid/package.json
src/packages/solid/vite.config.js
src/sandbox/package.json

fix: Remove ref from column, row - cleanup packages

---

package.json
pnpm-lock.yaml

fix: add back in renderer

---

pnpm-lock.yaml
src/packages/blits/.storybook/main.ts
src/packages/blits/.storybook/preview.ts
src/packages/blits/package-lock.json
src/packages/blits/package.json
src/packages/blits/src/components/Button/Button.stories.tsx
src/packages/blits/src/components/Button/Button.styles.ts
src/packages/blits/src/components/Button/Button.ts
src/packages/blits/tsconfig.json
src/packages/blits/vite.config.js
src/packages/solid/vite.config.js

This PR adds the following:
- Storybook
- Vite (and a first pass at its configuration)
- TypeScript
- Button
View the Button story and test its controls to make sure the component is properly rendered and responds correctly.

feat: set up storybook

---

src/packages/solid/components/Icon/Icon.styles.ts
src/packages/solid/components/Icon/Icon.tsx
src/packages/solid/components/Icon/Icon.types.ts
src/packages/solid/components/Icon/index.ts

- updates styles to new configuration
- creates types file for icon
make sure icon renders as it should

fix(Icon): updates styles to new configuration

---

src/packages/solid/components/Badge/Badge.stories.tsx
src/packages/solid/components/Badge/Badge.styles.ts
src/packages/solid/components/Badge/Badge.tsx
src/packages/solid/components/Badge/Badge.types.ts
src/packages/solid/components/Badge/index.ts

updates badge styles to match new configuration
- removed iconAlign from stories
- make sure badge renders as expected

feat(Solid): Badge updates styles

---

src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/Button/Button.tsx
src/packages/solid/components/Button/Button.types.ts
src/packages/solid/components/Button/index.ts

- updates button styles to new configuration
- adds button types file
- make sure Button renders as expected

fix(Solid): updates Button styles

---

src/packages/solid/components/Checkbox/Checkbox.styles.ts
src/packages/solid/components/Checkbox/Checkbox.tsx
src/packages/solid/components/Checkbox/Checkbox.types.ts
src/packages/solid/components/Checkbox/index.ts

-## Description
updates Checkbox styles to match new configuration
- make sure Checkbox renders as expected

fix(Solid): updates Checkbox styles

---

src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Row/Row.tsx

fix: remove onFocus prop as its on intrinsicNode and wrong type

---

src/packages/solid/components/Artwork/Artwork.types.ts
src/packages/solid/components/Label/Label.styles.ts
src/packages/solid/components/Label/Label.tsx
src/packages/solid/components/Label/Label.types.ts
src/packages/solid/components/Label/index.ts

- updates Label styles to match new configuration
- updates Label styles to match new configuration
- make sure Label renders as expected

fix(Solid): updates Label styles

---

src/packages/solid/components/Input/Input.stories.tsx
src/packages/solid/components/Input/Input.styles.ts
src/packages/solid/components/Input/Input.tsx
src/packages/solid/components/Input/Input.types.ts
src/packages/solid/components/Input/index.ts

updates badge styles to match new configuration
- removed iconAlign from stories
- make sure input renders as expected

fix(Solid): updates Input styles

---

src/packages/solid/components/Button/Button.styles.ts
src/packages/solid/components/Wave/Wave.stories.tsx
src/packages/solid/components/Wave/Wave.styles.ts
src/packages/solid/components/Wave/Wave.tsx
src/packages/solid/components/Wave/Wave.types.ts
src/packages/solid/components/Wave/index.ts

-Creates a wave component of which the animation is controlled by "toggleAnimation"
-Currently animation is controlled via chaining and setInterval to the duration of the chained animations. Once changes to renderer allow for looping of chained animations, this will be updated
- creates whole component
- notice how the wave works, test out different tones
- -review code

feat(Solid): Wave creates component

---

src/packages/solid/components/CardContent/CardContent.tsx
src/packages/solid/components/ProgressBar/ProgressBar.styles.ts
src/packages/solid/components/ProgressBar/ProgressBar.tsx
src/packages/solid/components/ProgressBar/ProgressBar.types.ts
src/packages/solid/components/ProgressBar/index.ts
src/packages/solid/components/Tile/Tile.tsx

updates progressBar styles to new config
- creates types file
- adds inline styles props
make sure progressBar renders as expected

fix(Solid): updates progressBar styles

---

src/packages/solid/components/Row/Row.styles.ts
src/packages/solid/components/Row/Row.tsx
src/packages/solid/components/Row/Row.types.ts
src/packages/solid/components/Row/index.ts

- updates Row styles to match new configuration
- make sure Row renders as expected

fix(Solid): updates row styles

---

src/packages/solid/components/Column/Column.stories.tsx
src/packages/solid/components/Column/Column.styles.ts
src/packages/solid/components/Column/Column.tsx
src/packages/solid/components/Column/Column.types.ts
src/packages/solid/components/Column/index.ts

- updates Column styles to match new configuration
- make sure Column renders as expected

fix(Solid): updates Column styles

---

src/packages/solid/components/Checkbox/Checkbox.types.ts
src/packages/solid/components/Radio/Radio.styles.ts
src/packages/solid/components/Radio/Radio.tsx
src/packages/solid/components/Radio/Radio.types.ts
src/packages/solid/components/Radio/index.ts

- updates Row styles to match new configuration
- make sure Row renders as expected

fix(Solid): updates Radio styles

---

src/packages/solid/components/Button/index.ts
src/packages/solid/components/Label/index.ts
src/packages/solid/index.ts

exposes utils and types to any application importing solid-ui

fix(Solid): includes utils in build

---

src/packages/solid/components/Metadata/Details.tsx
src/packages/solid/components/Metadata/index.ts
src/packages/solid/index.ts

fix(Solid): exposes details and ratings

---

src/packages/solid/components/Checkbox/Checkbox.styles.ts
src/packages/solid/components/Checkbox/Checkbox.types.ts
src/packages/solid/components/ProgressBar/ProgressBar.styles.ts

quick fix to resolve some type errors
- checkbox: comment out unused themeKeys, add border to style properties type
- progress bar: update borderRadius theme key to have the correct value

fix: comment out unused checkbox props, update ProgressBar themeKeys

---

src/packages/solid/components/Toggle/Toggle.stories.tsx
src/packages/solid/components/Toggle/Toggle.styles.ts
src/packages/solid/components/Toggle/Toggle.tsx
src/packages/solid/components/Toggle/Toggle.types.ts
src/packages/solid/components/Toggle/index.ts

- updates Toggle styles to match new configuration
- fixes style bug for background of toggle
- adds borderRadius to ever instance where border is
- make sure Toggle renders as expected

fix(Solid): updates Toggle styles

---

src/packages/solid/components/Metadata/Details.styles.ts
src/packages/solid/components/Metadata/Details.tsx
src/packages/solid/components/Metadata/Details.types.ts
src/packages/solid/components/Metadata/Metadata.styles.ts
src/packages/solid/components/Metadata/Metadata.tsx
src/packages/solid/components/Metadata/Metadata.types.ts
src/packages/solid/components/Metadata/Rating.styles.ts
src/packages/solid/components/Metadata/Rating.tsx
src/packages/solid/components/Metadata/Rating.types.ts
src/packages/solid/components/Metadata/index.ts
src/packages/solid/components/Tile/Tile.stories.tsx

updates Ratings, Details, and Metadata styles to match new configuration
##Changes
update styles
adds inline style properties
##Testing
make sure Metadata renders as expected

fix(Solid): updates Metadata styles

---

.github/workflows/publish-packages.yml
.github/workflows/publish-solid-storybook.yml
.github/workflows/smoke-test.yml
pnpm-lock.yaml

Updates scripts and lock file to pnpm 9

feat: update to pnpm 9, update workflows to use pnpm 9
